const recipes=[];
const emptyRecipe={id:'',name:'À planifier',tag:'rapide',image:'assets/pates-gratin.png',price:0,time:0,portions:4,note:'Ajoutez votre première recette'};
const days=['Lun. 29','Mar. 30','Mer. 31','Jeu. 1','Ven. 2','Sam. 3','Dim. 4'];
const plan=days.map(()=>({lunch:'À planifier',dinner:'',dad:true,liam:true,leftovers:'Aucun reste'}));
let currentFilter='all'; const stored=JSON.parse(localStorage.getItem('atable-plan')||'null'); let week=stored?.length===7?stored:plan; function save(){localStorage.setItem('atable-plan',JSON.stringify(week))} function r(id){return recipes.find(x=>x.id===id)||emptyRecipe} const label=t=>({xxl:'XXL & restes',rapide:'Rapide',gamelle:'Gamelle',dessert:'Dessert'})[t]||'Recette';
function budget(){const total=week.reduce((s,d)=>s+r(d.dinner).price,0)+95;document.querySelector('#budget-total').textContent=total;document.querySelector('#budget-left').textContent=`${170-total} € de marge`;document.querySelector('#budget-bar').style.width=`${total/170*100}%`;document.querySelector('#planned-budget').textContent=`${total-21} €`;document.querySelector('#full-budget').textContent=`${total} €`}
function renderWeek(){document.querySelector('#week-grid').innerHTML=week.map((d,i)=>{const dish=r(d.dinner),atHome=['Maman','Elio'];if(!d.dad)atHome.unshift('Papa');if(!d.liam)atHome.push('Liam');const portions=atHome.length===4?4:atHome.length===3?3:2;return `<article class="day-column"><div class="day-head"><strong>${days[i]}</strong><span>${i===4?'Courses en fin de journée':' '}</span></div><div class="meal-slot"><div class="slot-label">Midi</div><div class="meal-name">${d.lunch}</div><div class="meal-meta"><b>${atHome.join(' · ')}</b><br>${portions} portions à prévoir${d.dad?' + 1 gamelle':''}</div><div class="presence-buttons"><button class="presence ${d.dad?'active':''}" data-day="${i}" data-person="dad">Papa : ${d.dad?'gamelle':'maison'}</button><button class="presence ${d.liam?'active':''}" data-day="${i}" data-person="liam">Liam : ${d.liam?'cantine':'maison'}</button></div></div><div class="meal-slot"><div class="slot-label">Soir</div><div class="meal-name">${dish.name}</div><div class="meal-meta">${dish.time} min · ${dish.price} € · ${d.cook||dish.portions} portions préparées</div><div class="restes">${d.leftovers}</div></div></article>`}).join('');document.querySelectorAll('.presence').forEach(b=>b.onclick=()=>{week[b.dataset.day][b.dataset.person]=!week[b.dataset.day][b.dataset.person];if(typeof recomputePlan==='function')recomputePlan();save();renderWeek();shopping()});budget()}
function renderRecipes(){const shown=currentFilter==='all'?recipes:recipes.filter(x=>x.tag===currentFilter);document.querySelector('#recipe-grid').innerHTML=shown.length?shown.map(x=>`<article class="recipe-card"><img class="recipe-photo" src="${x.image}" alt="${x.name}"><span class="tag">${label(x.tag)}</span><h2>${x.name}</h2><p class="muted">${x.note}</p><div class="recipe-details"><span>⏱ ${x.time} min</span><span>💶 ${x.price} €</span><span>🍽 ${x.portions}</span></div></article>`).join(''):'<div class="empty-recipes"><h2>Aucune recette pour le moment</h2><p>Ajoutez une recette manuellement ou utilisez le bouton reçu par email.</p></div>'}
const ingredientRecipes={};
const staples={'Petit-déjeuner & goûters':[['Lait',4,'L'],['Céréales',1,'paquet'],['Fruits',2,'kg'],['Compotes',1,'lot']]};
function shopping(){const all={};week.forEach(day=>{const recipe=ingredientRecipes[day.dinner];if(!recipe)return;const factor=(day.cook||r(day.dinner).portions)/recipe.base;recipe.items.forEach(([name,quantity,unit,group])=>{const key=`${group}|${name}|${unit}`;all[key]=(all[key]||0)+quantity*factor})});Object.entries(staples).forEach(([group,items])=>items.forEach(([name,quantity,unit])=>{const key=`${group}|${name}|${unit}`;all[key]=(all[key]||0)+quantity}));const grouped={};Object.entries(all).forEach(([key,quantity])=>{const [group,name,unit]=key.split('|');(grouped[group]||=[]).push([name,quantity,unit])});document.querySelector('#shopping-list').innerHTML=Object.entries(grouped).map(([group,items])=>`<section class="shopping-group"><h3>${group}</h3>${items.sort().map(([name,quantity,unit])=>{const amount=Number.isInteger(quantity)?quantity:Math.round(quantity*10)/10;const id=`${group}-${name}-${unit}`;return `<label class="shopping-item"><input type="checkbox" data-k="${id}"><span>${name} · <b>${amount} ${unit}</b></span></label>`}).join('')}</section>`).join('');document.querySelectorAll('.shopping-item input').forEach(x=>{x.checked=localStorage.getItem(x.dataset.k)==='1';x.closest('label').classList.toggle('done',x.checked);x.onchange=()=>{localStorage.setItem(x.dataset.k,x.checked?'1':'0');x.closest('label').classList.toggle('done',x.checked)}})}
document.querySelectorAll('.nav-link').forEach(a=>a.onclick=e=>{e.preventDefault();document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===a.dataset.view));document.querySelectorAll('.nav-link').forEach(n=>n.classList.toggle('active',n===a))});document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{currentFilter=c.dataset.filter;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('selected',x===c));renderRecipes()});document.querySelector('#add-meal').onclick=()=>alert('Le choix d’un repas sera la prochaine amélioration.');document.querySelector('#new-recipe').onclick=()=>alert('Ajoutez votre première recette.');document.querySelector('#reset-shopping').onclick=()=>{document.querySelectorAll('.shopping-item input').forEach(x=>{x.checked=false;localStorage.removeItem(x.dataset.k);x.closest('label').classList.remove('done')})};renderWeek();renderRecipes();shopping();
