const groups=[
['xxl','assets/pates-gratin.png',['Spaghettis bolognaise','Bolognaise aux lentilles','Pâtes thon-tomate-parmesan','Pâtes jambon-crème-parmesan','Pâtes poulet-crème-champignons','Pâtes pesto-courgette','Coquillettes jambon-fromage','Gratin de pâtes jambon-parmesan','Gratin de pâtes au thon','Lasagnes bolognaise','Lasagnes aux légumes discrets','Gnocchis sauce tomate-mozzarella','Gnocchis jambon-crème','Macaronis au fromage','One-pot pasta poulet-tomate']],
['gamelle','assets/poulet-riz.png',['Riz au poulet sauce douce','Riz sauté œufs-jambon','Riz au thon et tomate','Riz aux lentilles et carottes','Risotto jambon-parmesan','Couscous doux au poulet','Semoule et boulettes sauce tomate','Hachis parmentier','Parmentier de thon','Pommes de terre farcies jambon-fromage','Gratin dauphinois avec jambon','Tartiflette douce','Poêlée pommes de terre-saucisse','Galettes de pommes de terre','Purée maison et saucisse','Poulet rôti, pommes de terre et carottes','Cuisses de poulet au four et riz','Émincé de poulet à la crème','Poulet sauce tomate et pâtes','Poulet au citron doux et semoule','Boulettes de bœuf sauce tomate','Steak haché, purée et légumes séparés','Saucisses-lentilles','Saucisses, purée et oignons','Chili doux bœuf-haricots rouges','Chili végétarien doux','Poisson pané, riz et petits pois','Parmentier de poisson','Brandade de poisson simplifiée','Thon chaud à la tomate avec riz']],
['rapide','assets/pates-gratin.png',['Omelette pommes de terre-fromage','Omelette jambon-fromage','Omelette aux pâtes restantes','Quiche sans pâte jambon-fromage','Quiche thon-tomate','Tarte tomate-fromage','Croque-monsieur','Croque pizza','Crêpes jambon-fromage','Galettes complètes œuf-jambon-fromage','Wraps poulet-fromage','Wraps thon-fromage','Burgers maison et potatoes','Hot-dogs maison','Pizza maison jambon-fromage','Soupe carotte-pomme de terre','Soupe poireau-pomme de terre','Velouté courgette-fromage frais','Purée carotte-pomme de terre','Purée patate douce-pomme de terre','Courgettes farcies au bœuf','Tomates farcies et riz','Endives au jambon','Gratin chou-fleur-béchamel-jambon','Gratin brocoli-fromage','Épinards à la crème, œuf et pommes de terre','Ratatouille douce avec riz','Poêlée de légumes avec poulet','Galettes de légumes râpés','Sauce tomate mixée aux légumes pour pâtes','Salade de pâtes thon-fromage','Salade de riz jambon-œufs','Salade de pommes de terre-thon','Taboulé maison','Cake salé jambon-fromage','Cake thon-tomate','Pain perdu salé jambon-fromage','Tartines chaudes jambon-fromage','Toasts œuf-fromage','Restes de poulet en sandwich','Restes de bolognaise en gratin','Restes de riz en riz sauté','Restes de purée en galettes','Restes de légumes en quiche','Soirée congélateur : portion XXL préparée d’avance']]];
const recipes=groups.flatMap(([tag,image,names],g)=>names.map((name,i)=>({id:`r${g}-${i}`,name,tag,image,price:tag==='xxl'?10+i%5:tag==='gamelle'?8+i%4:5+i%5,time:tag==='xxl'?45+i%3*15:20+i%4*10,portions:tag==='xxl'?8:tag==='gamelle'?6:4,note:tag==='xxl'?'Restes · congélation possible':tag==='gamelle'?'Se réchauffe bien · doux':'Rapide · adapté à la semaine'})));
const days=['Lun. 29','Mar. 30','Mer. 31','Jeu. 1','Ven. 2','Sam. 3','Dim. 4'];
const plan=[['Soupe & tartines','r0-7',true,true,'4 portions pour mardi'],['Restes de gratin','r1-15',true,true,'2 portions pour mercredi'],['Restes de lasagnes','r0-9',true,true,'3 portions pour jeudi'],['Restes de lasagnes','r2-0',true,true,'Aucun reste'],['Gamelle & cantine','r2-14',true,true,'Aucun reste'],['Pâtes thon-tomate-parmesan','r0-2',false,false,'2 portions pour dimanche'],['Restes de pâtes','r2-0',false,false,'Aucun reste']].map(([lunch,dinner,dad,liam,leftovers])=>({lunch,dinner,dad,liam,leftovers}));
let currentFilter='all'; const stored=JSON.parse(localStorage.getItem('atable-plan')||'null'); let week=stored?.length===7?stored:plan; if(week[6]?.dinner==='r2-0')week[6].dinner='r2-14'; if(week[5]?.dinner==='r1-7'){week[5].cook=8;week[5].leftovers='4 portions pour dimanche';} function save(){localStorage.setItem('atable-plan',JSON.stringify(week))} function r(id){return recipes.find(x=>x.id===id)||recipes[0]} const label=t=>({xxl:'XXL & restes',rapide:'Rapide',gamelle:'Gamelle'})[t];
function budget(){const total=week.reduce((s,d)=>s+r(d.dinner).price,0)+95;document.querySelector('#budget-total').textContent=total;document.querySelector('#budget-left').textContent=`${170-total} € de marge`;document.querySelector('#budget-bar').style.width=`${total/170*100}%`;document.querySelector('#planned-budget').textContent=`${total-21} €`;document.querySelector('#full-budget').textContent=`${total} €`}
function renderWeek(){document.querySelector('#week-grid').innerHTML=week.map((d,i)=>{const dish=r(d.dinner),atHome=['Maman','Elio'];if(!d.dad)atHome.unshift('Papa');if(!d.liam)atHome.push('Liam');const portions=atHome.length===4?4:atHome.length===3?3:2;return `<article class="day-column"><div class="day-head"><strong>${days[i]}</strong><span>${i===4?'Courses en fin de journée':' '}</span></div><div class="meal-slot"><div class="slot-label">Midi</div><div class="meal-name">${d.lunch}</div><div class="meal-meta"><b>${atHome.join(' · ')}</b><br>${portions} portions à prévoir${d.dad?' + 1 gamelle':''}</div><div class="presence-buttons"><button class="presence ${d.dad?'active':''}" data-day="${i}" data-person="dad">Papa : ${d.dad?'gamelle':'maison'}</button><button class="presence ${d.liam?'active':''}" data-day="${i}" data-person="liam">Liam : ${d.liam?'cantine':'maison'}</button></div></div><div class="meal-slot"><div class="slot-label">Soir</div><div class="meal-name">${dish.name}</div><div class="meal-meta">${dish.time} min · ${dish.price} € · ${d.cook||dish.portions} portions préparées</div><div class="restes">${d.leftovers}</div></div></article>`}).join('');document.querySelectorAll('.presence').forEach(b=>b.onclick=()=>{week[b.dataset.day][b.dataset.person]=!week[b.dataset.day][b.dataset.person];if(typeof recomputePlan==='function')recomputePlan();save();renderWeek();shopping()});budget()}
function renderRecipes(){const shown=currentFilter==='all'?recipes:recipes.filter(x=>x.tag===currentFilter);document.querySelector('#recipe-grid').innerHTML=shown.map(x=>`<article class="recipe-card"><img class="recipe-photo" src="${x.image}" alt="${x.name}"><span class="tag">${label(x.tag)}</span><h2>${x.name}</h2><p class="muted">${x.note}</p><div class="recipe-details"><span>⏱ ${x.time} min</span><span>💶 ${x.price} €</span><span>🍽 ${x.portions}</span></div></article>`).join('')}
const ingredientRecipes={
  'r0-7':{base:7,items:[['Pâtes',500,'g','Épicerie'],['Jambon',250,'g','Frais'],['Crème',40,'cl','Frais'],['Parmesan',120,'g','Frais'],['Fromage râpé',150,'g','Frais']]},
  'r1-15':{base:7,items:[['Cuisses de poulet',1.2,'kg','Frais'],['Riz',500,'g','Épicerie'],['Carottes',700,'g','Fruits & légumes'],['Crème',20,'cl','Frais']]},
  'r0-9':{base:7,items:[['Feuilles de lasagne',350,'g','Épicerie'],['Viande hachée',600,'g','Frais'],['Sauce tomate',800,'g','Épicerie'],['Lait',75,'cl','Frais'],['Fromage râpé',180,'g','Frais'],['Carottes',300,'g','Fruits & légumes']]},
  'r0-2':{base:7,items:[['Pâtes',550,'g','Épicerie'],['Thon en boîte',4,'boîtes','Épicerie'],['Sauce tomate',700,'g','Épicerie'],['Parmesan',100,'g','Frais']]},
  'r1-7':{base:8,items:[['Pommes de terre',1.8,'kg','Fruits & légumes'],['Viande hachée',650,'g','Frais'],['Lait',35,'cl','Frais'],['Fromage râpé',120,'g','Frais'],['Carottes',400,'g','Fruits & légumes']]},
  'r2-14':{base:4,items:[['Farine',500,'g','Épicerie'],['Sauce tomate',350,'g','Épicerie'],['Jambon',200,'g','Frais'],['Fromage râpé',250,'g','Frais'],['Mozzarella',250,'g','Frais']]}
};
const staples={'Petit-déjeuner & goûters':[['Lait',4,'L'],['Céréales',1,'paquet'],['Fruits',2,'kg'],['Compotes',1,'lot']]};
function shopping(){const all={};week.forEach(day=>{const recipe=ingredientRecipes[day.dinner];if(!recipe)return;const factor=(day.cook||r(day.dinner).portions)/recipe.base;recipe.items.forEach(([name,quantity,unit,group])=>{const key=`${group}|${name}|${unit}`;all[key]=(all[key]||0)+quantity*factor})});Object.entries(staples).forEach(([group,items])=>items.forEach(([name,quantity,unit])=>{const key=`${group}|${name}|${unit}`;all[key]=(all[key]||0)+quantity}));const grouped={};Object.entries(all).forEach(([key,quantity])=>{const [group,name,unit]=key.split('|');(grouped[group]||=[]).push([name,quantity,unit])});document.querySelector('#shopping-list').innerHTML=Object.entries(grouped).map(([group,items])=>`<section class="shopping-group"><h3>${group}</h3>${items.sort().map(([name,quantity,unit])=>{const amount=Number.isInteger(quantity)?quantity:Math.round(quantity*10)/10;const id=`${group}-${name}-${unit}`;return `<label class="shopping-item"><input type="checkbox" data-k="${id}"><span>${name} · <b>${amount} ${unit}</b></span></label>`}).join('')}</section>`).join('');document.querySelectorAll('.shopping-item input').forEach(x=>{x.checked=localStorage.getItem(x.dataset.k)==='1';x.closest('label').classList.toggle('done',x.checked);x.onchange=()=>{localStorage.setItem(x.dataset.k,x.checked?'1':'0');x.closest('label').classList.toggle('done',x.checked)}})}
document.querySelectorAll('.nav-link').forEach(a=>a.onclick=e=>{e.preventDefault();document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===a.dataset.view));document.querySelectorAll('.nav-link').forEach(n=>n.classList.toggle('active',n===a))});document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{currentFilter=c.dataset.filter;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('selected',x===c));renderRecipes()});document.querySelector('#add-meal').onclick=()=>alert('Le choix d’un repas sera la prochaine amélioration.');document.querySelector('#new-recipe').onclick=()=>alert('Les 90 recettes de départ sont chargées.');document.querySelector('#reset-shopping').onclick=()=>{document.querySelectorAll('.shopping-item input').forEach(x=>{x.checked=false;localStorage.removeItem(x.dataset.k);x.closest('label').classList.remove('done')})};renderWeek();renderRecipes();shopping();
