const recipeDialog=document.getElementById('recipe-dialog');
const recipeForm=document.getElementById('recipe-form');
let editingRecipe=null;

const savedRecipes=JSON.parse(localStorage.getItem('atable-recipes-v2')||'null');
if(Array.isArray(savedRecipes)){savedRecipes.forEach(saved=>{const recipe=recipes.find(item=>item.id===saved.id);if(recipe)Object.assign(recipe,saved)});renderRecipes();}

recipeForm.innerHTML=`<button class="dialog-close" value="cancel" aria-label="Fermer">×</button><p class="eyebrow">Fiche recette</p><h2 id="editor-title">Recette</h2><label>Nom<input required id="edit-name"></label><label>Ingrédients <small>(un par ligne, avec quantité)</small><textarea id="edit-ingredients" rows="5" class="form-control" placeholder="500 g pâtes\n200 g jambon\n100 g parmesan"></textarea></label><label>Coût estimé (€)<input required id="edit-price" type="number" min="0" step="0.5"></label><label>Temps (minutes)<input required id="edit-time" type="number" min="5"></label><label>Portions préparées<input required id="edit-portions" type="number" min="1"></label><label>Photo<select id="edit-image"><option value="assets/pates-gratin.png">Pâtes / gratin</option><option value="assets/poulet-riz.png">Poulet / riz</option></select></label><div class="dialog-actions"><button class="button" type="button" id="delete-recipe">Supprimer</button><button class="button" value="cancel">Annuler</button><button class="button primary" value="default">Enregistrer</button></div>`;

function openEditor(recipe){editingRecipe=recipe;document.getElementById('editor-title').textContent=recipe.name;document.getElementById('edit-name').value=recipe.name;document.getElementById('edit-ingredients').value=recipe.ingredients||'';document.getElementById('edit-price').value=recipe.price;document.getElementById('edit-time').value=recipe.time;document.getElementById('edit-portions').value=recipe.portions;document.getElementById('edit-image').value=recipe.image||'assets/pates-gratin.png';document.getElementById('delete-recipe').hidden=!recipe.custom;recipeDialog.showModal();}

document.getElementById('new-recipe').onclick=()=>openEditor({id:`custom-${Date.now()}`,name:'Nouvelle recette',ingredients:'',price:10,time:30,portions:4,image:'assets/pates-gratin.png',tag:'rapide',note:'À compléter',custom:true});
document.getElementById('recipe-grid').addEventListener('click',event=>{const card=event.target.closest('.recipe-card');if(!card)return;const name=card.querySelector('h2')?.textContent;const recipe=recipes.find(item=>item.name===name);if(recipe)openEditor(recipe);});
recipeForm.addEventListener('submit',event=>{event.preventDefault();event.stopImmediatePropagation();if(event.submitter?.value==='cancel'){recipeDialog.close();return;}Object.assign(editingRecipe,{name:document.getElementById('edit-name').value.trim(),ingredients:document.getElementById('edit-ingredients').value.trim(),price:Number(document.getElementById('edit-price').value),time:Number(document.getElementById('edit-time').value),portions:Number(document.getElementById('edit-portions').value),image:document.getElementById('edit-image').value});if(!recipes.includes(editingRecipe))recipes.push(editingRecipe);localStorage.setItem('atable-recipes-v2',JSON.stringify(recipes));renderRecipes();renderWeek();shopping();recipeDialog.close();},true);
document.getElementById('delete-recipe').onclick=()=>{const index=recipes.indexOf(editingRecipe);if(index>=0)recipes.splice(index,1);localStorage.setItem('atable-recipes-v2',JSON.stringify(recipes));renderRecipes();recipeDialog.close();};
